### ISSUE TITLE
[REQ] License set

### ISSUE THREAD

**Issue by MarcoRavich** [bfields/openwrt-recording#4]
Hi there,
since I've forked this repo into [hALSAmrec](https://github.com/MarcoRavich/hALSAmrec#readme) can you please set a GH-compliant (better if GPLv3, IMHO) license ?

Thanks in advance !

**Comment by bfields** [comment]
Yes, feel free to bug me again if I haven't done that in a few days....

**Comment by bfields** [comment]
Should be done.
